GET http://localhost:3000/

######################################

POST http://localhost:3000/login
Content-Type: 'application/json'

{
    "username":"aaru",
    "password":"aaru",
}

######################################

POST http://localhost:3000/register
Content-Type: 'application/json'

{
   "firstname":"a",
   "lastname":"a",
    "email":"a@gmail.com",
    "username":"aa",
    "password":"aa"
}